server:
  port: 8072

# Spring application configuration
spring:
  application:
    name: gateway-server
  config:
    import: 'optional:configserver:http://localhost:8071'
    # Spring Cloud Gateway configuration
  # This section defines the configuration properties for the Spring Cloud Gateway
  cloud:
    gateway:
      # Service discovery configuration
      # This section defines how the gateway discovers services
      discovery:
        # Locator settings
        # This section defines the settings for the service locator
        locator:
          # Enable the locator
          # This property enables the service locator, which allows the gateway to discover services
          enabled: false
          # Flag to indicate whether the service id should be in lower case
          # This property is used to control the case of the service id
          # Default value is false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: 'gateway-server'
    version: '1.0.0'
    description: 'Gateway description'

logging:
  level:
    in:
      cg: DEBUG